abstract: ''
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
build_requires: 
  Class::DBI: 0
  Class::DBI::Pager: 0
  Test::Base: 0
  Test::Dependencies: 0
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
name: Sledge-Plugin-Pager
no_index: 
  directory: 
    - inc
    - t
requires: 
  Lingua::EN::Inflect: 0
  String::CamelCase: 0
version: 0.01
